### ISSUE TITLE
Correct way to set color overrides? CmpItemKind GitSignsAddNr etc

### ISSUE THREAD

**Issue by benfrain** [EdenEast/nightfox.nvim#153]
Not an issue but trying to understand the 'correct' way to add overrides for my use case.

Previously, I was using this code to add the overrides I wanted:

```lua
vim.api.nvim_exec(
  [[
function! MyHighlights() abort
    highlight CursorLine guifg=NONE guibg=#353A54
    highlight CmpItemAbbr guifg=#9FA4B6
    highlight SpecialKey guibg=NONE
    highlight CmpItemKind guifg=#8289A0
    highlight CmpItemMenu guifg=#8289A0
    highlight PmenuSel guibg=#73daca guifg=#111111
    highlight Pmenu guibg=#2E3248
    highlight GitSignsAddNr guifg=#26A07A
    highlight GitSignsDeleteNr guifg=#E87D7D
    highlight GitSignsChangeNr guifg=#AD991F
    endfunction
augroup MyColors
    autocmd!
    autocmd ColorScheme * call MyHighlights()
augroup END]],
  true
)
```

But I'm sure there is a better way to add these changes in Nightfox?

Should I be adding these as module overrides in the setup function? Could someone provide an example of what the config would look like with one of these added correctly?

Thanks for any guidance.

**Comment by EdenEast** [comment]
Sure I can provide an example of what these would look like in nightfox's setup function.

```lua

require("nightfox").setup({
  groups = {
    CursorLine = { bg = "#353A54" },
    CmpItemAbbr = { fg = "#9FA4B6" },
    CmpItemKind = { fg = "#8289A0" },
    CmpItemMenu = { fg = "#8289A0" },
    PmenuSel = { bg = "#73daca", fg = "#111111" },
    Pmenu = { bg = "#2E3248" },
    GitSignsAddNr = { fg = "#26A07A" },
    GitSignsDeleteNr = { fg = "#E87D7D" },
    GitSignsChangeNr = { fg = "#AD991F" },
  },
})
```

I see that you have slightly changed the color values for some highlight groups. If you wanted for example to change the color used for the entire colorscheme you can override a `pallet` or `spec`. For example if you wanted to change the color of git add, delete and changed for all git highlight groups you could do something like:

```lua
require("nightfox").setup({
  specs = {
    nightfox = {
      git = {
        add = "#26A07A",
        removed = "#E87D7D",
        changed = "#AD991F",
      },
    },
  },
})
```

See the `:help` or usage for references to what a [palette](https://github.com/EdenEast/nightfox.nvim/blob/main/usage.md#palette) and [spec](https://github.com/EdenEast/nightfox.nvim/blob/main/usage.md#spec) are.

When I added per style override I did not add that for `groups` I can see where someone would also want to override for a specific style instead of everything. I could see about changing that so that the setup() functions works the same palettes specs and groups.

Also here is an example of doing your overrides with `vim.api`

```lua
local function custom_highlights()
  vim.api.nvim_set_hl(0, "CursorLine", { bg = "#353A54" })
  vim.api.nvim_set_hl(0, "CmpItemAbbr", { fg = "#9FA4B6" })
  vim.api.nvim_set_hl(0, "CmpItemKind", { fg = "#8289A0" })
  vim.api.nvim_set_hl(0, "CmpItemMenu", { fg = "#8289A0" })
  vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#73daca", fg = "#111111" })
  vim.api.nvim_set_hl(0, "Pmenu", { bg = "#2E3248" })
  vim.api.nvim_set_hl(0, "GitSignsAddNr", { fg = "#26A07A" })
  vim.api.nvim_set_hl(0, "GitSignsDeleteNr", { fg = "#E87D7D" })
  vim.api.nvim_set_hl(0, "GitSignsChangeNr", { fg = "#AD991F" })
end

vim.api.nvim_create_augroup("CustomHighlights", { clear = true })
vim.api.nvim_create_autocmd("ColorScheme", {
  callbacks = custom_highlights,
})
```

Hope this answer helped and let me know if you have another other questions I can help you with.

**Comment by benfrain** [comment]
That's perfect, thanks for providing such an in-depth answer. Got it exactly how I want it now. Thank You!

**Comment by EdenEast** [comment]
Relates: #154

**Comment by EdenEast** [comment]
Just a note. I just merged a change that aligns `groups` to be like the rest of the override options.


```lua


require("nightfox").setup({
  groups = {
    all = {
      CursorLine = { bg = "#353A54" },
      CmpItemAbbr = { fg = "#9FA4B6" },
      CmpItemKind = { fg = "#8289A0" },
      CmpItemMenu = { fg = "#8289A0" },
      PmenuSel = { bg = "#73daca", fg = "#111111" },
      Pmenu = { bg = "#2E3248" },
      GitSignsAddNr = { fg = "#26A07A" },
      GitSignsDeleteNr = { fg = "#E87D7D" },
      GitSignsChangeNr = { fg = "#AD991F" },
    },
  },
})
```
