### ISSUE TITLE
Independent/multiple setup-like calls

### ISSUE THREAD

**Issue by gegoune** [EdenEast/nightfox.nvim#166]
**Is your feature request related to a problem? Please describe.**
To override/create new highlight groups one has to include them all in single `.setup({…})` call. Those highlight groups more often than not are parts of some group - be it plugin related, status/win-bar related, etc. With current way of doing things one cannot easily use night fox's api to create those highlight group for example in separate lua script alongside relevant context (plugin, etc).

**Describe the solution you'd like**
API call to add highlight groups same way the `.setup({ groups = { _fox_ = { … } })` does. It should be possible to call it multiple times adding/overriding highlight groups. I can think of something like: `.append|add|extra({})`. That would allow users to put, for example all neovim native highlight groups into `.setup()` call and plugin specific ones, for example, in `plugins/telescope.lua`.

**Describe alternatives you've considered**
Keep all highlight groups in `setup()` — do nothing.

**Additional context**
NA

**Comment by EdenEast** [comment]
The `setup` function can be called multiple times. The `setup` function is just a wrapper around nightfox's internal
settings store. The table passed to the `setup` function is deep copied into the store.


## Example

```lua
-- lua/plugins/telescope.lua
require('nightfox').setup({
  groups = {
    all = {
      TelescopeMatching = { link = "Search" },
    }
  }
})

-- lua/plugins/neogit.lua
require('nightfox').setup({
  groups = {
    all = {
      NeogitBranch = { fg = "diag.warn" },
    }
  }
})
```

```lua
-- Resulting nightfox value store
print(vim.inspect(require('nightfox.override').groups))

{
  all = {
    NeogitBranch = {
      fg = "diag.warn",
      link = ""
    },
    TelescopeMatching = {
      link = "Search"
    }
  }
}
```

**Comment by gegoune** [comment]
Ah, awesome, wasn't aware of that - did I miss it from documentation? That is really amazing, thanks!

**Comment by gegoune** [comment]
One more question: how would you go about automating `.clean()` and `.compile()` for such distributed setup?

**Comment by EdenEast** [comment]
Reading the documentation does not make this well known. This can be added to the documentation.

As for automating `.clean()` and `.compile()` function I am not sure on the best day to do that. The compile file is just an optimization so that nightfox does not have to compute the highlight groups each time you load vim.

I could see maybe computing some hash from a users config and check if there is a compiled file with the same hash. Although I am not sure how performant that would be compared to just calling the compile function ever so often when updating any highlight groups or a new clone.

**Comment by EdenEast** [comment]
Reading the documentation does not make this well known. This can be added to the documentation.

As for automating `.clean()` and `.compile()` function I am not sure on the best day to do that. The compile file is just an optimization so that nightfox does not have to compute the highlight groups each time you load vim.

I could see maybe computing some hash from a users config and check if there is a compiled file with the same hash. Although I am not sure how performant that would be compared to just calling the compile function ever so often when updating any highlight groups or a new clone.

**Comment by gegoune** [comment]
Indeed, didn't appear straight forward due to fact that those calls can be in multiple places. Will just add user command to wrap clean and compile.

Thanks!

**Comment by EdenEast** [comment]
You do now need to call `clean` then `compile`. Clean just removes the compile files. This is good when you want to iterate your config. `compile` will override any previous generated files.
