### ISSUE TITLE
Feline/Tabby Theme Setup?

### ISSUE THREAD

**Issue by alteredorange** [EdenEast/nightfox.nvim#172]
I'm very new to Neovim and plugins, so please forgive me if this is completely obvious!

I'm trying to apply the nightfox themes to feline and tabby. I tried requiring just the files in your readme, but nothing happened. I then downloaded your entire `eden/modules` folder and tried requiring it from init.vim like so:
```
Plug 'feline-nvim/feline.nvim'
Plug 'EdenEast/nightfox.nvim'
...
:lua require'feline'.setup()
:lua require('eden/modules/ui/feline')
```
But that still didn't change the look of feline. How would I go about applying your config? Thanks so much for the help, loving the look of Nightfox!

**Comment by EdenEast** [comment]
For lua, `require` uses `.` as module separators instead of path separators. For a great resource on using lua with neovim checkout @nanotree great [guide](https://github.com/nanotee/nvim-lua-guide).

My personal configuration is non-trivial as I use some helper functions I have defined myself (say for defining autocmds). It also calls `feline.setup()` from my feline module so your first require would not be required.

If you are looking for a single file that would contain everything you would need to get my config results I could add an example of that.

**Comment by alteredorange** [comment]
Yes, a single file example would be super helpful! I also noticed you used Packer, where I'm using vim-plug. The weird thing is, I got it reading those lua files, because If I changed the path, it would say those files don't exist, but even in the right path, the theme doesn't change.

**Comment by EdenEast** [comment]
I just merged a pr that added a single file example of my feline and tabby configuration. If you have issues with it let me know.

**Comment by alteredorange** [comment]
Awesome, that did the trick! Thanks so much for the help and the awesome theme, I'm rocking now!
