### ISSUE TITLE
Getting errors in compiler.lua saying that a local file is 'nil'

### ISSUE THREAD

**Issue by Abhi6** [EdenEast/nightfox.nvim#261]
I am not exactly sure what is wrong, but I am getting the following error
`E5113: Error while calling lua chunk: ...packer/start/nightfox.nvim/lua/nightfox/lib/compiler.lua:73: attempt to index local 'file' (a nil value)
stack traceback:`
Basically, I looked into that specific in that file, and I saw that it was `file:write(require("nightfox").compiled)` in that line, and so I assume (I am not proficient in lua, just getting by with what I need to know to configure neovim) that the program is trying to get a file named `nightfox`. However, when I look in that directory, there is no file named `nightfox`.

I uninstalled the plugin with Packer and reinstalled it to see if that would make a difference (in case I accidentally deleted the file or something), but I am still getting the same issue.

Can anyone help?

**Comment by EdenEast** [comment]
It looks like `file` is not being created. Could you let me know the following:

- Are you updated to the latest changes?
- What is your platform?
- What version of neovim?
- Does the cache folder exist?
  -  `~/.cache/nvim/nightfox` for mac and linux
  - `%localappdata%\nvim\nightfox` for windows

**Comment by nullchilly** [comment]
@EdenEast Consider adding some error handling

https://github.com/catppuccin/nvim/commit/4c5a2ebb250c2e3f1a6a05f372fead0a0988981e

![image](https://user-images.githubusercontent.com/56817415/204876160-25783adc-c5e9-4d0a-ac0d-df64d810bb92.png)

**Comment by EdenEast** [comment]
Thanks @nullchilly for your help. That is a great idea and something that I will add. I have some notes on the commit:

- The tmp file is being written to `/tmp` but is not checked for windows.
  - Would use `os.getenv("TMP")` for windows. (using `TMP` instead of `TEMP` as that is what powershell checks)
- You added this for the neovim compiler version but forgot about the vim one

Also, do you have an example of breaking the compiler to produce the error. I cant come up with one without breaking something else that is not the compiler.
