### ISSUE TITLE
broken yaml syntax highlighting

### ISSUE THREAD

**Issue by vadimi** [EdenEast/nightfox.nvim#262]
## Description

Hello, I've noticed, that after https://github.com/EdenEast/nightfox.nvim/pull/241 yaml syntax highlighting no longer works. I've tried 1 commit before that using vim plug and it worked fine.

## Behavior

**Expected behavior**

working yaml syntax highlighting

**Screenshots**
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1156106/204634723-2f47b6c3-6016-40c6-bc86-44e26f2c007f.png">

## Configuration

Relevant nightfox's configuration...

**Reproduce**

1. open any yaml file

**Comment by vadimi** [comment]
actually, it's this commit - https://github.com/EdenEast/nightfox.nvim/commit/bb70a6489c6055f445a86a0290ead288732477df

**Comment by EdenEast** [comment]
I am unable to reproduce your issue. On the left is the current master and on the right is me going back to commit https://github.com/EdenEast/nightfox.nvim/commit/15f3b5837a8d07f45cbe16753fbf13630bc167a3 which is from mid October.

![Screen Shot 2022-11-29 at 3 38 45 PM](https://user-images.githubusercontent.com/2746374/204642771-b651efbd-852e-42e4-a735-9a943766e17c.png)

This was using neovim 0.8. Also this is using the vim syntax highlighting because the yaml treesitter parser does not support highlighting.

```
>> default         context_commentstring  highlight  incremental_selection  indent  playground  query_linter  
yaml               ✓                      ✗          ✗                      ✗       ✓           ✗             
```

**Comment by vadimi** [comment]
I just noticed that when I comment out this line in `lua/nightfox/group/modules/treesitter.lua` and run `:NightfoxCompile` it works for me. And it looks like json syntax is also impacted:

`["@field.yaml"]             = { fg = spec.func }, -- For fields.`

**Comment by EdenEast** [comment]
What treesitter Grammer are you using that supports highlighting?

**Comment by vadimi** [comment]
I'm using just standard `nvim-treesitter` config and yaml highlighting _wasn't_ disabled. I guess I was ok with how nightfox highlighted it by default (see my screenshot). I just disabled it and now it looks like your screenshot :) 

I think the issue can be closed. And thanks for the great theme!
