### ISSUE TITLE
Missing highlights for clojure keywords

### ISSUE THREAD

**Issue by misterzirillo** [EdenEast/nightfox.nvim#291]
## Description

Clojure keywords (eg `:keyword`) seem to be missing color. This does not seem to be the case with a raw symbol like `'my-symbol`.

## Behavior

**Expected behavior**
Keywords have some color. Treesitter sees them as `@symbol`

**Screenshots**
![image](https://user-images.githubusercontent.com/4575207/210903947-d1def249-5302-47f6-a90c-6a55c9fc1c0c.png)

## Configuration

I am using AstroNvim, although I have observed this issue without it.

```lua
-- in user/init.lua
config = {
  -- ...
  colorscheme = "nightfox",
  plugins = {
    init = {
        ["EdenEast/nightfox.nvim"] = {}
    },
  },
}

```

**Comment by EdenEast** [comment]
Nightfox only defines the colors for highlight groups. Treesitter is the one that does the syntax highlighting. Your issue is with the treesitter parser for clojure.

I am also unable to reproduce your issue. [@symbol](https://github.com/EdenEast/nightfox.nvim/blob/main/lua/nightfox/group/modules/treesitter.lua#L86) is defined as preproc. By default that is defined as [pink](https://github.com/EdenEast/nightfox.nvim/blob/main/lua/nightfox/palette/nightfox.lua#L73).

![image](https://user-images.githubusercontent.com/2746374/210926884-045ff0ea-4863-403f-a1f4-f319f7347ae2.png)

Do you have a reproducible example?

**Comment by misterzirillo** [comment]
I tried a completely bare neovim config and it seems to work. Looks like the problem is with Astro somehow, so I'll close this and tinker some more.
