### ISSUE TITLE
bug: non-yellow color for carbonfox alacritty configuration file

### ISSUE THREAD

**Issue by halshar** [EdenEast/nightfox.nvim#402]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-2050+gc4acbb87b

### Operating system/version

Fedora Linux - 39

### Describe the bug

The yellow hex code for the carbonfox alacritty config is not exactly yellow, for the normal, bright, and the dim sections the hex code for yellow color is as follows
```toml
[colors.normal]
yellow = "#08bdba"

[colors.bright]
yellow = "#2dc7c4"

[colors.dim]
yellow = "#07a19e"
```

the above hex codes are not exactly yellow but more on the blue side as seen below
![image](https://github.com/EdenEast/nightfox.nvim/assets/45795416/ac1f9369-50e8-4755-b551-6f476a44227f)

have checked that the yellow hex codes for other themes for alacritty config are either shade of yellow or orange

with the above config the yellow color looks like blue(checked with the neofetch color palette), if this is the expected hex code then please close the issue

### Steps To Reproduce

1. replace the current/default alacritty.toml code with carbonfox's config

### Expected Behavior

the yellow color should be yellow

**Comment by EdenEast** [comment]
This is expected, carbonfox was a port of [oxocarbon](https://github.com/nyoom-engineering/oxocarbon.nvim) when it was originally written in rust. This was ported so that others did not have to have rust installed to use the colorscheme.

You can see that in the screenshots that there is no yellow ex:

![carbonfox](https://user-images.githubusercontent.com/2746374/183569670-91260cab-83a9-4247-8e09-6abb46c52152.png)
![nightfox](https://user-images.githubusercontent.com/2746374/158456286-9e3ee657-60e6-49d8-b85e-dcab285b31c3.png)

The colors come from the palette file:

https://github.com/EdenEast/nightfox.nvim/blob/1e650316680a777fb50e4ab35d82ecf32da485b8/lua/nightfox/palette/carbonfox.lua#L14-L23

<img width="404" alt="image" src="https://github.com/EdenEast/nightfox.nvim/assets/2746374/8bd07a7d-6898-45b7-b87a-b5ac960b17ac">
